const $=id=>document.getElementById(id);const fmt=n=>n==null?'—':new Intl.NumberFormat().format(n);const date=v=>v?new Date(v).toLocaleString(): '—';
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json()}
function activity(target,rows,type){if(!rows.length)return;$(target).innerHTML=rows.slice(0,6).map(x=>{const evidence=x.details?.decision_scorecard?.score,ai=x.details?.external_ai_review?.viability_score;const scores=type==='decision'&&evidence!=null?` · evidence ${evidence}/100${ai!=null?` · AI ${ai}/100`:''}`:'';return `<div class="activity-row"><span class="symbol">${x.symbol||'—'}</span><div><strong>${type==='decision'?x.strategy||x.reason:x.side||'ticket'}</strong><small>${date(x.created_at_utc)}${scores}</small></div><span class="state">${type==='decision'?x.final_decision:x.status}</span></div>`}).join('')}
function renderShadow(data){$('runtime').textContent=data.runtime_storage==='database'?'PostgreSQL':'Local files';$('storage').textContent=data.runtime_storage||'unknown';const s=data.states||{},report=s.consolidated?.available?s.consolidated:null,refresh=s.refresh?.available?s.refresh:null,breakout=s.breakout?.available?s.breakout:null,ml=s.breakout_ml_filter?.available?s.breakout_ml_filter:null;
  $('last-refresh').textContent=refresh?date(refresh.generated_at_utc):'Not run';$('refresh-feed').textContent=refresh?`${refresh.feed||'unknown'} feed · ${refresh.results?.length||0} timeframes`:'Awaiting scheduled job';
  $('quality').textContent=report?(report.quality_passed?'Passed':'Needs attention'):'Unavailable';$('quality-detail').textContent=report?`${Object.keys(report.data_quality||{}).length} timeframes checked`:'Waiting for refresh';
  if(breakout){$('breakout-completed').textContent=fmt(breakout.completed_trades);$('breakout-pending').textContent=fmt(breakout.pending_trades);$('profit-factor').textContent=breakout.metrics?.profit_factor==null?'—':Number(breakout.metrics.profit_factor).toFixed(2);$('breakout-state').textContent=breakout.minimum_sample_reached?'Review due':'Collecting';const n=breakout.completed_trades||0;$('sample-label').textContent=`${n} / 100`;$('sample-progress').style.width=`${Math.min(100,n)}%`;const sessions=breakout.completed_by_entry_session||{};$('sessions').innerHTML=Object.entries(sessions).map(([k,v])=>`<span>${k}: ${v.trades??v.count??0} trades</span>`).join('')}
  if(ml){$('ml-scored').textContent=fmt(ml.scored_candidates);$('ml-allowed').textContent=fmt(ml.allowed_candidates);$('ml-rejected').textContent=fmt(ml.rejected_candidates);$('ml-threshold').textContent=`${Math.round((ml.threshold||0)*100)}%`}
  const quality=report?.data_quality||{};$('candle-table').innerHTML=Object.entries(quality).length?Object.entries(quality).map(([tf,q])=>`<tr><td><strong>${tf}</strong></td><td>${fmt(q.rows)}</td><td>${fmt(q.symbols)}</td><td>${date(q.first)}</td><td>${date(q.last)}</td><td class="check ${q.duplicates||q.bad_timestamps||q.bad_ohlc?'bad':''}">${q.duplicates||q.bad_timestamps||q.bad_ohlc?'Check data':'Passed'}</td></tr>`).join(''):'<tr><td colspan="6">The Railway refresh job has not populated candle status yet.</td></tr>'}
async function load(){const button=$('refresh');button.disabled=true;try{const [health,ready,shadow,risk,decisions,tickets]=await Promise.all([json('/health'),json('/ready'),json('/shadow/status'),json('/risk/status'),json('/decisions?limit=6'),json('/tickets?limit=6')]);$('system-dot').className='status-dot ok';$('system-label').textContent='System online';$('system-detail').textContent=`${health.service} is connected and ready.`;$('mode').textContent=`${ready.execution_mode} mode`;$('risk').textContent=risk.kill_switch?'Kill switch active':(risk.daily_pause?'Daily pause':'Within limits');$('risk-detail').textContent=`$${fmt(risk.open_risk)} open risk · ${risk.trades_count} trades`;renderShadow(shadow);activity('decisions',decisions,'decision');activity('tickets',tickets,'ticket');$('updated').textContent=`Updated ${new Date().toLocaleTimeString()}`}catch(e){$('system-dot').className='status-dot bad';$('system-label').textContent='Connection problem';$('system-detail').textContent=e.message}finally{button.disabled=false}}
setInterval(()=>$('clock').textContent=new Date().toLocaleString(),1000);$('refresh').addEventListener('click',load);load();setInterval(load,60000);
